Repository binaryblaze040/kindness-kitchen, pull requests merged in 2024-02, with the labels that each got.

#1 removed default html code
  src/app/app.component.html
Labels: refactor

#2 created basic code structure
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.routes.ts
  src/components/homepage/homepage.component.html
  src/components/homepage/homepage.component.scss
  src/components/homepage/homepage.component.spec.ts
  src/components/homepage/homepage.component.ts
  src/components/navbar/navbar.component.html
  src/components/navbar/navbar.component.scss
  src/components/navbar/navbar.component.spec.ts
  src/components/navbar/navbar.component.ts
Labels: refactor code base

#3 added navbar ui
  .prettierrc
  package-lock.json
  package.json
  src/components/homepage/homepage.component.html
  src/components/navbar/navbar.component.html
  src/components/navbar/navbar.component.scss
  src/main.ts
  src/styles.scss
  tsconfig.app.json
  tsconfig.spec.json
Labels: enhancement

#4 added homepage layout
  .eslintrc.json
  angular.json
  package-lock.json
  package.json
  src/assets/icons/homepage/dish.svg
  src/assets/icons/homepage/gift.svg
  src/assets/images/homepage/hero-banner.png
  src/components/homepage/homepage.component.html
  src/components/homepage/homepage.component.scss
  src/variables/style/layout-variables.scss
Labels: enhancement, refactor code base

#5 updated navbar ui
  src/app/app.component.ts
  src/app/app.routes.ts
  src/assets/images/navbar/happy-coin.png
  src/assets/images/navbar/header-logo.png
  src/components/navbar/navbar.component.html
  src/components/navbar/navbar.component.scss
  src/components/navbar/navbar.component.ts
  src/components/receive-food/receive-food.component.html
  src/components/receive-food/receive-food.component.scss
  src/components/receive-food/receive-food.component.spec.ts
  src/components/receive-food/receive-food.component.ts
Labels: enhancement, refactor code

#6 added donate food component with routing
  src/app/app.component.ts
  src/app/app.routes.ts
  src/components/component-index.ts
  src/components/donate-food/donate-food.component.html
  src/components/donate-food/donate-food.component.scss
  src/components/donate-food/donate-food.component.spec.ts
  src/components/donate-food/donate-food.component.ts
  src/components/homepage/homepage.component.html
  src/components/homepage/homepage.component.ts
  src/components/navbar/navbar.component.html
  src/components/navbar/navbar.component.ts
Labels: enhancement

#7 scrollbar and lint fixes
  src/components/homepage/homepage.component.html
  src/components/navbar/models/navbar-model.ts
  src/components/navbar/navbar.component.html
  src/components/navbar/navbar.component.ts
  src/styles.scss
  src/variables/style/layout-variables.scss
Labels: refactor code
